name: oryn_cli
description: Command Line Interface (CLI) for Oryn (a fast, light-weight web framework in dart)
version: 1.0.0
homepage: https://github.com/atrox39/Oryn-Cli
repo: https://github.com/atrox39/Oryn-Cli

environment:
  sdk: '>=2.14.0 <4.0.0'

dependencies:
  watcher: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0

executables:
  oryn:
